propel:
  _attributes:        { package: plugins.nahoWikiPlugin.lib.model }
  
  naho_wiki_page:
    _attributes:      { phpName: nahoWikiPage }
    id:               ~
    name:             { type: varchar, size: 255, index: unique }
    latest_revision:  { type: integer, required: true, default: 1 }
  
  naho_wiki_revision:
    _attributes:      { phpName: nahoWikiRevision }
    created_at:       ~
    page_id:          { type: integer, foreignTable: naho_wiki_page, foreignReference: id, required: true, onDelete: cascade, primaryKey: true }
    revision:         { type: integer, required: true, default: 1, primaryKey: true }
    user_name:        { type: varchar, size: 255, required: true }
    comment:          { type: varchar, size: 255 }
    content_id:       { type: integer, foreignTable: naho_wiki_content, foreignReference: id, required: true, onDelete: cascade, primaryKey: true }
  
  naho_wiki_content:
    _attributes:      { phpName: nahoWikiContent }
    id:               ~
    content:          { type: longvarchar } # uncompressed content
    gz_content:       { type: blob } # compressed content
